### PR TITLE
add lodestar to content hashes

### PR DESCRIPTION
**Pull request by alexpeterson91**

### CODE REVIEW

**Comment by nflaig** [comment]
@alexpeterson91 @pablomendezroyo it this an important changes and do we need to release this before adding Lodestar to the Stakers UI?

**Comment by pablomendezroyo** [comment]
> @alexpeterson91 @pablomendezroyo it this an important change and do we need to release this before adding Lodestar to the Stakers UI?

This can only be merged once lodestar mainnet (`lodestar.dnp.dappnode.eth`) has been published.

The content hashes feature is a file with the IPFS hashes from the ethereum clients, that in case of not having access to an Ethereum Client, allows dappnode user to install the client by downloading the content from IPFS using the corresponding IPFS hash.

**Comment by pablomendezroyo** [comment]
Depends on Lodestar to be published

See https://github.com/dappnode/DAppNodePackage-Lodestar

**Comment by nflaig** [comment]
@pablomendezroyo thanks for the clarification. We can publish Lodestar mainnet package once https://github.com/dappnode/DAppNodePackage-Lodestar/pull/44 is merged, I am already testing it for almost a week. To make it fully work (without workarounds) need to also publish few ELs and web3signer

**Pull request merged**
